/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'juergen.stumpp' at '21.07.16 18:03' with Gradle 2.14.1
 *
 * @author juergen.stumpp, @date 21.07.16 18:03
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
